name: Test and Enforce Deno Format

on:
  pull_request

jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
          deno-version: 1.0.5
      - name: Test Deno Template
        run: deno test --allow-net
      - name: Enforce Deno Format
        run: if [[ $(deno fmt) ]]; then exit 1; fi